export { default as Banner } from './components/banner/banner'
export { default as Button } from './components/button/button'
export { default as Card } from './components/card/card'
export { default as Faq } from './components/faq/faq'
export { default as Header } from './components/header/header'
export { default as Jumbotron } from './components/jumbotron/jumbotron'
export { default as Section } from './components/section/section'
export { default as GlobalStyles } from './components/head/styles'
