export { default as Button } from './components/button/button'
export { default as Head } from './components/global/'
export { default as Header } from './components/header/header'
export { default as Jumbotron } from './components/jumbotron/jumbotron'
export { default as Section } from './components/section/section'
